# Generated by Django 3.1.1 on 2020-09-06 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
